make clean
make TYPE_of_INDEX=_SI_4p TYPE_of_BOUNDARY=_101 H_MODEL=SI M_MODEL=LXVnW
make clean
make TYPE_of_INDEX=_SEnI_6p TYPE_of_BOUNDARY=_101 H_MODEL=SEnI M_MODEL=LXVnW
make clean
make TYPE_of_INDEX=_NO_CASES_7p TYPE_of_BOUNDARY=_101 H_MODEL=NO_CASES M_MODEL=LXVnW
make clean
make TYPE_of_INDEX=_CASES_1_11p TYPE_of_BOUNDARY=_101 H_MODEL=CASES_1 M_MODEL=LXVnW
make clean