### Building H-M models where the comlexity of the mosquito part varies
### while the human part is always NO_CASES (SEnIR)

make clean
make CPG=CPGPLOT_REPRESENTATION FILE=FILE_REPRESENTATION TYPE_of_INDEX=_NO_CASES_LXVnW_9p TYPE_of_BOUNDARY=_333 H_MODEL=NO_CASES M_MODEL=LXVnW
make clean
make CPG=CPGPLOT_REPRESENTATION FILE=FILE_REPRESENTATION TYPE_of_INDEX=_NO_CASES_XkVnW_7p TYPE_of_BOUNDARY=_333 H_MODEL=NO_CASES M_MODEL=XkVnW
make clean
make CPG=CPGPLOT_REPRESENTATION FILE=FILE_REPRESENTATION TYPE_of_INDEX=_NO_CASES_XVnW_6p TYPE_of_BOUNDARY=_333 H_MODEL=NO_CASES M_MODEL=XVnW
make clean
make CPG=CPGPLOT_REPRESENTATION FILE=FILE_REPRESENTATION TYPE_of_INDEX=_NO_CASES_XW_4p TYPE_of_BOUNDARY=_333 H_MODEL=NO_CASES M_MODEL=XW
make clean
