### Building H-M models where the comlexity of the human part varies
### while the mosquito part is always LXVnW
make clean
make CPG=NON_CPGPLOT_REPRESENTATION TYPE_of_INDEX=_SI_3p TYPE_of_BOUNDARY=_111 H_MODEL=SI M_MODEL=LXVnW
make clean
make CPG=NON_CPGPLOT_REPRESENTATION TYPE_of_INDEX=_SEnI_5p TYPE_of_BOUNDARY=_111 H_MODEL=SEnI M_MODEL=LXVnW
make clean
make CPG=NON_CPGPLOT_REPRESENTATION TYPE_of_INDEX=_NO_CASES_6p TYPE_of_BOUNDARY=_111 H_MODEL=NO_CASES M_MODEL=LXVnW
make clean
make CPG=NON_CPGPLOT_REPRESENTATION TYPE_of_INDEX=_CASES_1_10p TYPE_of_BOUNDARY=_111 H_MODEL=CASES_1 M_MODEL=LXVnW
make clean
