make clean
make TYPE_of_INDEX=_Hu_4p TYPE_of_MAIN=_SUBDOMINANT M_MODEL=LXVnW H_MODEL=CASES_1 JACOBIAN=ODE
make clean
make TYPE_of_INDEX=_Ca_4p TYPE_of_MAIN=_SUBDOMINANT M_MODEL=LXVnW H_MODEL=CASES_1 JACOBIAN=ODE
make clean
make TYPE_of_INDEX=_Mo_4p TYPE_of_MAIN=_SUBDOMINANT M_MODEL=LXVnW H_MODEL=CASES_1 JACOBIAN=ODE
make clean
make TYPE_of_INDEX=_Pa_4p TYPE_of_MAIN=_SUBDOMINANT M_MODEL=LXVnW H_MODEL=CASES_1 JACOBIAN=ODE
make clean
# make clean
# make TYPE_of_INDEX=_Hu_4p TYPE_of_MAIN=_SUBPLOTS
# make clean
# make TYPE_of_INDEX=_Ca_4p TYPE_of_MAIN=_SUBPLOTS
# make clean
# make TYPE_of_INDEX=_Mo_4p TYPE_of_MAIN=_SUBPLOTS
# make clean
# make TYPE_of_INDEX=_Pa_4p TYPE_of_MAIN=_SUBPLOTS
# make clean
# make TYPE_of_INDEX=_Hu_4p TYPE_of_MAIN=_SUBPLOTS H_MODEL=NO_CASES
# make clean
# make TYPE_of_INDEX=_Ca_4p TYPE_of_MAIN=_SUBPLOTS H_MODEL=NO_CASES
# make clean
# make TYPE_of_INDEX=_Mo_4p TYPE_of_MAIN=_SUBPLOTS H_MODEL=NO_CASES
# make clean
# make TYPE_of_INDEX=_Pa_4p TYPE_of_MAIN=_SUBPLOTS H_MODEL=NO_CASES
